spring:
  datasource:
    url: jdbc:postgresql://autorack.proxy.rlwy.net:32866/railway


    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate